### ISSUE TITLE
1.53 bin unpack (DEV server)

### ISSUE THREAD

**Issue by hornet331** [klensy/wt-tools#7] opened 2015-10-14 15:22 UTC
Hi just want to let you know that unpacking bins are not working anymore with 1.53.
Dev server just got released today and when trying to unpack them following error shows:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py"
, in <module>
  File "vromfs_unpack.py", line 190, in <module>
  File "vromfs_unpack.py", line 186, in main
  File "vromfs_unpack.py", line 109, in unpack
  File "vromfs_unpack.py", line 79, in decomp_and_write
zlib.error: Error -3 while decompressing data: incorrect header check

**Comment by klensy** [comment] 2015-10-14 17:56
It will be nice, if you upload *vromfs.bin files somewhere and give me the link.

**Comment by hornet331** [comment] 2015-10-14 19:37
ah ok, I would have uploaded them if needed.

**Comment by jalba69** [comment] 2015-10-14 21:45
Hi,
First let me say a big thank you for those tools, really great to explore the hidden side of the game, thanks to you for making this possible.

Now the issue, 
there is now in 1.53 an error message with the ddx_unpack looking a bit like the one above so it might be linked, steps to reproduce :

- Unpack some dxp.bin of a plane, no issues here.
- Trying to unpack one of the .ddsx obtained and i get this  :

-----
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "ddsx_unpack.py", line 77, in <module>
  File "ddsx_unpack.py", line 71, in main
  File "ddsx_unpack.py", line 53, in unpack
zlib.error: Error -3 while decompressing data: unknown compression method
-----

or it's due to the new rendering with PBR that added some data and not recognized by the extractor,  i don't know :

Again thanks a lot for your work.

**Comment by klensy** [comment] 2015-10-15 14:11
Dev version on your files? I have 1.53.6.6 only.

**Comment by jalba69** [comment] 2015-10-15 15:00
Hi, it updated today for 1.53.6.8 but i had the issue on 1.53.6.6, tested with the same files after updating and now it seems to work, more or less, some files work fine, some others get out corrupted.

For example decompressing the "content\pkg_main\res\pkg_main_aircrafts\a7m1.dxp.bin" 
then from this folder some ddsx files like the a7m1_n_dmg.ddsx is now accepted by the ddx unpacker but it ends up corrupted.

Yesterday on version 1.63.6.6 all the files from this same package was giving me the error messages.

Don't know what is wrong but seems like some files might be corrupted, maybe it's on the game side and not the extracting tools themselves, if so i'm sorry for the false alarm, i will continue to test a bit the files later when I'll have time and see what is going on.

Thanks a lot.

**Comment by klensy** [comment] 2015-10-15 15:08
As i mentioned on main page of this repository, not all ddsx files will unpack properly.

**Comment by tealmill** [comment] 2015-10-15 15:58
Is there an ETA on when could you possibly get the unpacker working with 1.53 aces.vromfs.bin?

Is there some kind of a big problem?

**Comment by klensy** [comment] 2015-10-15 17:42
>Unpack some dxp.bin of a plane, no issues here.
>Trying to unpack one of the .ddsx obtained and i get this

On which file you get that error? I tried on random dxp file (spain.dxp.bin), and all looks like ok.

**Comment by jalba69** [comment] 2015-10-15 17:59
Like i said a bit earlier, I had the error on the decompressed file "content\pkg_main\res\pkg_main_aircrafts\a7m1.dxp.bin" with all the ddsx extracted from it when trying to unpack them into dds, this was with patch 1.53.6.6 , now with patch 1.53.6.8 most of the ddsx files are extractable with the ddsx_unpack tool , only the _dmg one seems to be end up corrupted but as you said some files may not unpack properly it may be normal to have those corrupted.

Thanks.

**Comment by klensy** [comment] 2015-10-16 18:52
>Is there an ETA

No. For now, i cant recognize compressing pattern for fromfs files, so need more investigating.

**Comment by hornet331** [comment] 2015-10-24 21:51
any progress on this issue, or is it likely that you have to drop this feature from your tools?

**Comment by klensy** [comment] 2015-10-24 21:59
No progress for now. When 1.53 patch will be installed on production servers - will look closely with full client (no, only vromfs files insufficiently), now i wouldn't download test client, haven't disk space for it )

**Comment by klensy** [comment] 2015-11-06 16:37
So, found some info about new vromfs files, hope i can update unpacker.

**Comment by 3316556** [comment] 2015-11-06 19:45
YAAAY

**Comment by 3316556** [comment] 2015-11-07 03:20
any progress?

**Comment by mike10d** [comment] 2015-11-07 03:31
I can only guess, but [these things, they take time.](https://www.youtube.com/watch?v=0d6yBHDvKUw)

**Comment by 3316556** [comment] 2015-11-10 19:05
If you have time, can you make a video tut for the python method? no rush, just a suggestion.

**Comment by klensy** [comment] 2015-11-23 19:49
So, tnx to @MasterModeley, algo revealed and Soon™, unpacker will be fixed.

**Comment by MasterModeley** [comment] 2015-11-23 19:54
You know where to find me :) Please contact, if that.

**Comment by jalba69** [comment] 2015-11-25 11:23
That's great news, thanks for the hard work guys.

can't wait to verify a few strange things and compare some 1.53 values with what we had before...

Thanks a lot.

**Comment by 3316556** [comment] 2015-12-09 01:55
Soon™  Indeed.....

**Comment by MasterModeley** [comment] 2015-12-09 05:27
[vromfs.zip](https://github.com/klensy/wt-tools/files/56376/vromfs.zip)

**Comment by 3316556** [comment] 2015-12-09 06:51
cool tnx m8 good work!

**Comment by hornet331** [comment] 2015-12-09 19:26
Wice work, good to see it working again.

**Comment by SoulMaril** [comment] 2015-12-29 13:52
I am able to unpack the files but I think I am missing something. Are we able to decode the blk files of 1.55?

**Comment by klensy** [comment] 2015-12-29 14:28
Uhh, there 1.55 version. Old blk unpacker can't process them? Can u unpack old blk's?

**Comment by SoulMaril** [comment] 2015-12-29 14:40
Hmm... Didn't tried before. 
...Yes I am able to unpack them. Thank you very much.

**Comment by klensy** [comment] 2016-11-24 17:40
Hurray!
One year and 2kk$ and unpacker updated.

But:
1. This version in `wrpl_unpack_with_construct` branch
2. Unpacking of old version dropped, but maybe restored, if i found old vromfs files
3. Not all vromfs type files unpacked (but most interest is)
4. Need to use custom compiled library, till PR to to this library will be accepted

Should work, but test it please.

**Comment by jalba69** [comment] 2016-11-24 17:51
How old do you need the vrfoms? 
I think i still have some stored from around 1.51 to 1.53 and 1.55 versions i think, not touched the game since maybe 6 months but glad to help if i can , just et me know if those versions are the ones you search for and i'll try to upload some .

**Comment by klensy** [comment] 2016-11-24 17:56
Any before 1.53, when unpacker stop working.

**Comment by jalba69** [comment] 2016-11-24 18:07
Here you go , all i have from 1.51 : http://www.mediafire.com/file/5vplo49664vup4w/1.51.rar

I'll try to look into my backup NAS when I'll be home this weekend to see if i have some older stuff there but i doubt i have older ones than this.

Hope it will be good enough.

**Comment by klensy** [comment] 2016-11-26 01:04
@jalba69 
Thanks, restored support of pre 1.53 vromfs.

Btw,
This is exe version for testing: http://rgho.st/8VkTLb57K

**Comment by klensy** [comment] 2016-12-26 19:14
Uploaded release v0.2 get it from [here](https://github.com/klensy/wt-tools/releases/tag/0.2).

**Closed by klensy** 2016-12-26 19:14 UTC
